sqlite: 
  name: usersDataBase
  type: sqlite
  path: /home/cmx/QtProjects/mxChat/data/users.db

mysql: 
  name: mysqlDataBase
  type: mysql
  host: 127.0.0.1
  port: 33060
  user: cmx
  password: 123456
  schema: mxchat
  # 允许最大连接数
  max_connections: 200
  #允许连接失败的次数
  max_connect_errors: 10
  default_authentication_plugin: mysql_native_password
  # 创建新表时将使用的默认存储引擎
  default-storage-engine: INNODB
  # 设置mysql客户端默认字符集
  default-character-set: utf8


redis: 
  name: redisDataBase
  type: redis
  host: 127.0.0.1
  port: 6379